//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAndes.ICC5103._202301.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enajenacion
    {
        public int Id { get; set; }
        public string CNE { get; set; }
        public string Comuna { get; set; }
        public string Manzana { get; set; }
        public string RolPredial { get; set; }
        public string Enajenantes { get; set; }
        public string Adquirientes { get; set; }
        public string Foja { get; set; }
        public System.DateTime FechaInscripcion { get; set; }
        public string NumeroInscripcion { get; set; }
    }
}
