
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace UAndes.ICC5103._202301.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Persona
{

    public int Id { get; set; }

    public string Rut { get; set; }

    public string Nombre { get; set; }

    public System.DateTime FechaNacimiento { get; set; }

    public string Email { get; set; }

    public string Dirección { get; set; }

}

}
